### ISSUE TITLE
Problems with distinct kana corresponding to the same romaji

### ISSUE THREAD

**Issue by eudahYah** [jorgecastillo/KanaDrill#14]
In Hiragana Drill and Katakana Drill, it can happen that two of the four answer buttons have the same label, but one of them is counted as right and the other as wrong. The reason for this is that e.g. both "じ" and "ぢ" have the same romaji transliteration "ji".

**Comment by jorgecastillo** [comment]
Thanks for your input. I'll fix this on the weekend.

**Comment by jorgecastillo** [comment]
I am sorry that it took me a year to fix this @eudahYah
