### ISSUE TITLE
Feature request: add table of all kana

### ISSUE THREAD

**Issue by axelsimon** [jorgecastillo/KanaDrill#19]
Hi,
I think the app could benefit from having an easily accessible table of all the katakana on one hand, and all the hiragana on the other.
Sometimes, all you want is to quickly look up a kana.

(No I'm not going to suggest the same for the kanji ;) )

Thanks!

**Comment by bmenant** [comment]
Great idea! It might be even more useful if those tables were displayed following a more conventional grid layout, such as [Gojūon](https://en.wikipedia.org/wiki/Goj%C5%ABon)... So far, it's pretty hard to read.
