### ISSUE TITLE
"Displaying order" not clear wording

### ISSUE THREAD

**Issue by landry314** [jorgecastillo/KanaDrill#5]
i figured out what "Displaying order" meant in the settings but it is not clear from the way it is written. i would rewrite it like this:

Display possible answers:
randomly
alphabetically

now, i am not sure if "alphabetically" is the right word as it is not an "alphabet". maybe there is a better word to describe the order on a table of kana...

**Comment by jorgecastillo** [comment]
I never though about it but it does sound more user friendly this way.
