### ISSUE TITLE
Kanji section displays japanese when a wrong answer is chosen

### ISSUE THREAD

**Issue by landry314** [jorgecastillo/KanaDrill#6]
in the Kanji Drill section when you choose a wrong answer you get a dialog with the right answer then you are looking at a screen with a bunch of japanese on the buttons you just saw. i do not understand this. what does it mean? it should be in english AND japanese maybe? also, the english choices that WERE there are not there anymore so... i mean... what is the point of this? this seems like this section is still in alpha development...

**Comment by jorgecastillo** [comment]
First of all, I want to thank you for your feedback & for taking the time to write it down. It's the reading of the kanji ( http://en.wikipedia.org/wiki/List_of_j%C5%8Dy%C5%8D_kanji ). Yeah you're right I think I will separate them. Well if you get the answer right it doesn't ask twice, so if you failed the Japanese reading but not the English meaning next time the ordered between both is not synchronized. More or less the whole app is in alpha :-)
