### ISSUE TITLE
Feature idea : full keyboard

### ISSUE THREAD

**Issue by KaitoKito** [jorgecastillo/KanaDrill#8]
Hi,

Thanks for that app, it helps me killing time and learn japanese on the same time.
Can you add an option to displays all kanas possible instead of just four ? It make the guess a bit harder, some people (like me) will like it.

Also on the 1.1.1 version (from Fdroid) the app had a nice black theme, but it went full white on the 1.1.4. Can you allow users to choose between both on the settings ? White background are paintul to see on a long period of time.

Thank you again for this app.

**Comment by jorgecastillo** [comment]
I want to thank you for your valuable feedback. You can change the theme now. About the first part I'll think about it, so the the issue will be left open.

**Comment by jorgecastillo** [comment]
I think I like it better with four option so I'll leave it as is.

**Comment by KaitoKito** [comment]
Hi,
Thanks for your work on the themes. On which version will it be available ? (I just installed the 1.1.6 but didn't see the option, please apologise me if I missed it).
Regarding the full keyboard idea, why not also make it as an option on the settings menu ? Assuming it's not a hard work to program it, I think letting the user choose himself would be the best.

Anyway I like how you displayed the different ways of training on the main page, it's better than before. The Hiragana/Katakana training mode are very good, nice work on them
Btw there's a typo on "Kaji Drill Japanese".

I wish you a nice day,
Kaito.

**Comment by jorgecastillo** [comment]
From 1.1.7 upwards. I will reopen this, so I have present this feautre but I don't expect to get this done i the near future. You have a nice day too!

**Comment by jorgecastillo** [comment]
I don't think I'll ever get around to implement this.
