### ISSUE TITLE
Feature: Writing training

### ISSUE THREAD

**Issue by sample2** [jorgecastillo/KanaDrill#9]
Thank you for making a FOSS app for Japanese learning.
I wanted to request a Japanese character writing training like this: https://play.google.com/store/apps/details?id=com.legendarya.helloandroid

**Comment by jorgecastillo** [comment]
Thanks for your feedback!

In the future[1] I will incorporate this:
http://commons.wikimedia.org/wiki/Category:Hiragana_stroke_order
http://commons.wikimedia.org/wiki/Category:Animations_of_katakana

And maybe this:
http://www.kanjicafe.com/license.htm

Of course this would have to be optional downloads, as not everyone may like the increased storage needed.

[1] Don't expect this before January :-)

**Comment by jorgecastillo** [comment]
Seem like to much work for some functionality I won't use so I am closing this.
